### ISSUE TITLE
Strange glyphs displayed when using private use area (PUA) 

### ISSUE THREAD

**Issue by cormullion** [justvanrossum/fontgoggles#385]
When you display glyphs from the Private Use Area U+F000 ... you see strange glyphs in the list at the left and the text entry field:

<img width="1940" alt="fontgoggles" src="https://github.com/justvanrossum/fontgoggles/assets/52289/e622dbaa-d73f-42ca-b86d-93d7e2e18fda">

I'm interested to know what they are. 😀🤔

**Comment by justvanrossum** [comment]
I have no idea, this is rendered by the OS.

**Comment by kenmcd** [comment]
That looks like the Apple Times.ttc file - which is not OpenType.
If you extract the TTFs from the TTC, you can open them in FontCreator and FontLab 8 (not 7) - but they are a complete mess.
And the FontCreator developer says they have bad check sums.
Dumping the TTF with `ttx` results in multiple "excess bytes" warnings when dumping the `glyf` table.
These errors prevent the fonts from working/installing in other operating systems - so they could just be Apple sabotage.

@cormullion These non-standard Apple fonts are the problem.

@justvanrossum Perhaps a warning is appropriate when fonts are opened which contain non-standard tables (`feat` `morx` etc.). Or is FG supporting this non-OpenType stuff?

**Comment by cormullion** [comment]
> These non-standard Apple fonts are the problem.

It's the same with any ttf font - I just chose Times because it's in the system.

**Comment by justvanrossum** [comment]
FontGoggles uses HarfBuzz, which does support various Apple specific features.

But indeed, this issue is about the UI text, which is rendered by the OS, so FontGoggles has no influence on that.

**Comment by cormullion** [comment]
Ok, you can close this if you like. My curiosity can go unsatisfied (for now)... 😀

**Comment by khaledhosny** [comment]
You probably installed a font that has glyphs for these characters and for some reason the UI toolkit font fallback is using it which is rather unusual since a well behaving font fallback system should skip PUA since there meaning is tied a specific font and fallback to ad different font makes no sense.

If you go to FontBook and search for any of these characters, it should tell you which fonts has them. My system has two fonts that support U+F000 but I get what looks like a `.notdef` glyph when I paste it into FontGoggles text input field, so no fallback is happening for me. May be your system UI font does actually support these characters?

**Comment by cormullion** [comment]
> You probably installed a font that has glyphs for these characters and for some reason the UI toolkit font fallback is using it which is rather unusual since a well behaving font fallback system should skip PUA since there meaning is tied a specific font and fallback to ad different font makes no sense.

@khaledhosny Thanks - I think you've solved this. For the first two Private Use Areas, MacOS displays question marks for the first one, but uses fallback fonts for the second one. I was picking up weird glyphs from FairFax and a Nerd Font. I agree these fonts' PUA glyphs probably shouldn't be used in this context.
