### ISSUE TITLE
View full character set

### ISSUE THREAD

**Issue by jackjennings** [justvanrossum/fontgoggles#59]
It would be great to have a way that one could look at the full character set of the currently viewed font file. (I don't think that you can currently do this, but I stand to be corrected.)

Without knowing what's included in the font, it doesn't seem possible to easily discover what's in it without typing random characters into the text box.

**Comment by justvanrossum** [comment]
See my answer at #56...

**Comment by justvanrossum** [comment]
In short maybe maybe in a future future version, but right now this is out of scope.

**Comment by jackjennings** [comment]
Maybe it's worth keeping this open, since it seems like this is a "common" request.

I'm not sure that this is something that doesn't belong in this application though, but maybe I don't understand the target audience.

Here's the use case that I hoped font googles would help with: I'm working as a web developer and I have a WOFF file provided by the foundry; I'd love to know if we'd gain any bandwidth savings by looking into subsetting the file; Font Book doesn't let me open a WOFF file. In terms of just understanding the thing that we're working with, it would be a huge help to be able to dig into the file and see what's in there.

**Comment by justvanrossum** [comment]
Good point.

The target audience is font developers who want to proof their fonts behavior, either from generated binary fonts or from ufos or designspace files. FontGoggles is designed to work in conjunction with a font editor, so the font developer knows the character and glyph set.

That said, I agree that it's a useful feature, it's just not planned right now for the 1.x series. I will reconsider once a 2.0 becomes a realistic prospect.

**Comment by davelab6** [comment]
> FontGoggles is designed to work in conjunction with a font editor, so the font developer knows the character and glyph set.

While this is the primary use case, the tool has become widely adopted, and so I propose a secondary use case is now valid, to use it as a sort of local version of https://wakamaifondue.com. 

The text input has a cog menu on the right to load/forget a text file; this suggests to me a separator and then a "generate complete text" option which produces a complete set of unicodes to display all shaped glyphs; that in turn suggests line wrapping, and overlay/offset comparison. I can also see a "classic" glyph palette/table view of all the glyphs, which could also be populated by all glyphs rather than a text input.

**Comment by davelab6** [comment]
I ran into this again today, where I want to see the full glyph sets of a couple of fonts to compare them interactively... A glyph picker, with a Select All (Cmd-A) ability, is something I'm reaching for and not finding :)
